name: CI Build

on:
  workflow_call:
    inputs:
      # For backwards compatibility
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: ''
    secrets:
      ACCESS_TOKEN:
        required: false

permissions: {}

jobs:
  ci-build:
    name: CI Build
    if: ${{ github.repository_owner == 'youlandinc' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }}"
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN != '' && secrets.ACCESS_TOKEN || null }}
      - name: Set up pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 10.17.0
      - name: Use specific Node.js version
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        if: ${{ inputs.node-version != '' }}
        with:
          node-version: ${{ inputs.node-version }}
      - name: Use Node.js version from repo
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        if: ${{ inputs.node-version == '' }}
        with:
          node-version-file: 'package.json'
          # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Run lint check
        run: pnpm lint

      - name: Run TypeScript check
        run: npx tsc --noEmit

      - name: Build application
        run: pnpm build
        env:
          NODE_OPTIONS: --max_old_space_size=6144
